dist: trusty
sudo: false
language: php

php:
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install: travis_retry composer install

script:
  - ./vendor/bin/phpcs

jobs:
  allow_failures:
    - php: nightly
